# Site settings
title: Jane Marczewski
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    You can usually find me singing songs, pounding a piano & not being chased by scary monsters
baseurl: "" # the subpath of your site, e.g. /blog/
url: "janemarczewski.github.io" # the base hostname & protocol for your site
twitter_username: janemarczewski
github_username:  jekyll

# Build settings
markdown: kramdown

exclude: ["node_modules", "package.json", "Gruntfile.js"]
