# Site settings
title: Jane Marczewski
email: jane.marczewski@gmail.com
description: "You can usually find me singing songs, pounding a piano & not being chased by scary monsters"
baseurl: ""
url: "janemarczewski.github.io"

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['node_modules', 'scss', 'feed.xml']
