# Site settings
title: Jane Marczewski
email: jane.marczewski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    You can usually find me singing songs, pounding a piano & working hard to be honest and cool at the same time. And just so you know, I'm glad you're here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "janemarczewski.github.io" # the base hostname & protocol for your site
twitter_username: janemarczewski

# Build settings
markdown: kramdown

exclude: ["node_modules", "package.json", "Gruntfile.js"]
